theme = "catppuccin_latte"

[editor]
bufferline = "always"
line-number = "relative"
idle-timeout = 0
completion-trigger-len = 1
completion-timeout = 0
completion-replace = true
end-of-line-diagnostics = "hint"

[editor.soft-wrap]
wrap-indicator = ""
enable = true

[editor.lsp]
auto-signature-help = false

[editor.statusline]
left = []
right = []

[editor.inline-diagnostics]
cursor-line = "warning"
other-lines = "warning"

[keys.normal]
"A-j" = ["extend_to_line_bounds", "delete_selection", "paste_after"]
"A-k" = [
  "extend_to_line_bounds",
  "delete_selection",
  "move_line_up",
  "paste_before",
]

[keys.normal.space]
q = ":quit!"
w = ":write"
x = ":write-quit!"
b = { c = ":buffer-close", f = "buffer_picker" }
